name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t jtlrules/express-web-app:latest
    - name: Push the Docker image
      run: docker push jtlrules/express-web-app:latest
    - name: Run Docker image
      run: docker run -p 80:80 jtlrules/express-web-app:latest
    - name: run Liatrio tests
      uses: liatrio/github-actions/apprentice-action@master
    - name: Push the Docker image
      run: docker push jtlrules/express-web-app